### ISSUE TITLE
Android app not able to sync folders

### ISSUE THREAD

**Issue by bsbudhwar** [afterlogic/aurora-files-flutter#2]
Hi,

In your mobile app only individual file upload option is there, there should be an option to select folders for sync or the default folder of mobile like Images, Documents, Downloads, Music, Snapshots etc should be automatically selected.

but in your app only Folder creation option is there no folder selection for sync option there in your app.

Please add an option to select folders to sync with mobile app.

**Comment by afterlogic-support** [comment]
That's not currently possible. Aurora Files doesn't sync files with mobile device, but merely offers an interface of accessing your file storage in [WebMail Pro](https://afterlogic.com/webmail-client), [Aurora Files](https://afterlogic.org/aurora-files) or [Aurora Corporate](https://afterlogic.com/aurora). You can select specific files for offline use but that's it.

**Comment by bsbudhwar** [comment]
Hi, okay sync is not required but there should be an option to upload folder or folders. Like it's giving option to upload files.
